IssueTracker/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from main import views as main_views
from accounts import views as accounts_views
from tickets import views as forum_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', main_views.get_index, name='index'),
    url(r'^faq/$', main_views.get_faq, name='faq'),
    url(r'^about/$', main_views.get_about, name='about'),
    url(r'^contact/$', main_views.get_contact, name='contact'),
    url(r'^register/$', accounts_views.register, name='register'),
    url(r'^profile/$', accounts_views.profile, name='profile'),
    url(r'^login/$', accounts_views.login, name='login'),
    url(r'^logout/$', accounts_views.logout, name='logout'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^forum/$', forum_views.forum),
    url(r'^tickets/(?P<subject_id>\d+)/$', forum_views.tickets, name='tickets'),
    url(r'^ticket/(?P<ticket_id>\d+)/$', forum_views.ticket, name='ticket'),
    url(r'^ticket/new/(?P<subject_id>\d+)/$',  forum_views.new_ticket, name='new_ticket'),
    url(r'^ticket/edit/(?P<ticket_id>\d+)/$',  forum_views.edit_ticket, name='edit_ticket'),
    url(r'^ticket/vote/(?P<ticket_id>\d+)/(?P<subject_id>\d+)/$', forum_views.ticket_vote, name='cast_vote'),
    url(r'^ticket/customdonate/(?P<ticket_id>\d+)/(?P<subject_id>\d+)/$', forum_views.custom_donate, name='custom_donate'),
    url(r'^post/new/(?P<ticket_id>\d+)/$', forum_views.new_post, name='new_post'),
    url(r'^post/edit/(?P<ticket_id>\d+)/(?P<post_id>\d+)/$',forum_views.edit_post, name='edit_post'),
    url(r'^post/delete/(?P<ticket_id>\d+)/(?P<post_id>\d+)/$', forum_views.delete_post, name='delete_post'),
    url(r'^profile/cards/add/$', accounts_views.add_card, name='add_card'),
    url(r'^profile/cards/delete/(?P<card_id>card_.*)/$', accounts_views.delete_card, name='delete_card'),
    url(r'^profile/cards/default/(?P<card_id>card_.*)/$', accounts_views.set_default_card, name='set_default_card'),
    url(r'^report/voting/(?P<subject_id>\d+)/$', forum_views.voting_results, name='voting_results'),
    url(r'^report/dashboard/$', forum_views.dashboard, name='dashboard'),
    url(r'^rest/work/', include('work.urls')),
]

tickets/urls.py
from django.conf.urls import url

work/urls.py
from django.conf.urls import url
from .views import LogCustomView

urlpatterns = [
    url(r'^log/custom/$', LogCustomView.as_view()),
]

polls/models.py
"""
Models for saving polls, poll options, and votes to the database
"""
from django.db import models
from django.conf import settings
from tickets.models import Subject, Ticket


class Poll(models.Model):
    """
    Poll consists of a poll question and subject type (e.g. Bug, Feature)
    """
    question = models.TextField()
    subject = models.OneToOneField(Subject, null=True, on_delete='models.CASCADE')

    def __unicode__(self):
        return self.question


class PollOption(models.Model):
    """
    Poll options consist of a poll and corresponding ticket to be voted on
    """
    poll = models.ForeignKey(Poll, related_name='options', on_delete='models.CASCADE')
    ticket = models.OneToOneField(Ticket, related_name='options', on_delete='models.CASCADE')

    def __unicode__(self):
        return self.name


class Vote(models.Model):
    """
    Votes consist of the poll the vote is being used for, the option in that poll,
    and the user that voted.
    """
    poll = models.ForeignKey(Poll, related_name='votes', on_delete='models.CASCADE')
    option = models.ForeignKey(PollOption, related_name='votes',
                               on_delete='models.CASCADE')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='votes',
                             on_delete='models.CASCADE')

threads/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings


class Subject(models.Model):
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name

class Thread(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads',on_delete='models.CASCADE')
    subject = models.ForeignKey(Subject, related_name='threads',on_delete='models.CASCADE')
    created_at = models.DateTimeField(default=timezone.now)

class Post(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts',on_delete='models.CASCADE')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts',on_delete='models.CASCADE')
    created_at = models.DateTimeField(default=timezone.now)

tickets/models.py
"""
Models for saving subjects, tickets (bug or feature), and posts to the database
"""

from django.db import models
from django.utils import timezone
from django.conf import settings
from tinymce.models import HTMLField


class Subject(models.Model):
    """
    Subject consists of a name and a description
    """
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name


class Ticket(models.Model):
    """
    Ticket consists of a name, description, user, subject, creation date, and status
    """
    NEW = 'NEW'
    ASSIGNED = 'ASSIGNED'
    OPEN = 'OPEN'
    FIXED = 'FIXED'
    RETEST = 'RETEST'
    REOPENED = 'REOPENED'
    VERIFIED = 'VERIFIED'
    BLOCKED = 'BLOCKED'
    CLOSED = 'CLOSED'
    STATUS_CHOICES = (
        (NEW, 'New'),
        (ASSIGNED, 'Assigned'),
        (OPEN, 'Open'),
        (FIXED, 'Fixed'),
        (RETEST, 'Retest'),
        (REOPENED, 'Reopened'),
        (VERIFIED, 'Verified'),
        (BLOCKED, 'Blocked'),
        (CLOSED, 'Closed'),
    )
    name = models.CharField(max_length=255, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='tickets',
                             on_delete='models.CASCADE')
    subject = models.ForeignKey(Subject, related_name='tickets', on_delete='models.CASCADE')
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=11, choices=STATUS_CHOICES, default=NEW)
    description = HTMLField()

    def __unicode__(self):
        return self.name


class Post(models.Model):
    """
    Post consists of a ticket, comment, username, and creation date
    """
    ticket = models.ForeignKey(Ticket, related_name='posts', on_delete='models.CASCADE')
    comment = HTMLField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts',
                             on_delete='models.CASCADE')
    created_at = models.DateTimeField(default=timezone.now)


class Bug(models.Model):
    """
    Bug consists of a ticket
    """
    ticket = models.OneToOneField(Ticket, on_delete='models.CASCADE')


class Feature(models.Model):
    """
    Feature consists of a ticket, donation goal, and total donations received
    """
    ticket = models.OneToOneField(Ticket, on_delete='models.CASCADE')
    donation_goal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_donations = models.DecimalField(max_digits=10, decimal_places=2, default=0)

threads/forms.py
from django import forms
from .models import Thread, Post


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)
    
    class Meta:
        model = Thread
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['comment']

tickets/forms.py
"""
Form that create/modify bug and feature tickets and posts
"""

from django import forms
from django.core.exceptions import ValidationError
from .models import Ticket, Post, Feature, Bug


class TicketForm(forms.ModelForm):
    """
    Ticket form
    """
    name = forms.CharField(label='Title')
    class Meta:
        """
        Fields to include on form
        """
        model = Ticket
        fields = ['name', 'description', 'status']

    def __init__(self, *args, **kwargs):
        """
        Set init details for Ticket form
        :return: Disable the status field on form
        """
        super(TicketForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)

        #if a brand new ticket, then disable status and donation goal
        if instance.id is None:
            self.fields['status'].disabled = True

    def clean_name(self):
        """
        Validates ticket name does not exist in database
        :return: validated ticket name
        """
        name = self.cleaned_data.get('name')
        if Ticket.objects.filter(name=name).exists() and self.instance.id is None:
            message = 'This ticket name already exists. Please choose another one. '
            raise ValidationError(message)

        return name

    def clean_description(self):
        """
        Validates description field is not left blank
        :return: validated description text
        """
        description = self.cleaned_data.get('description')
        if description is None:
            message = 'Description is required and cannot be left blank. '
            raise ValidationError(message)

        return description

class PostForm(forms.ModelForm):
    """
    Post form
    """
    class Meta:
        """
        Fields to include on form
        """
        model = Post
        fields = ['comment']


class FeatureForm(forms.ModelForm):
    """
    Feature ticket form
    """
    class Meta:
        """
        Fields to include and exclude on form
        """
        model = Feature
        fields = ['donation_goal']
        exclude = ['total_donations']

    def __init__(self, *args, **kwargs):
        """
        Set init details for Feature form
        :return: Disable the donation goal field on form
        """
        super(FeatureForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)

        #if a brand new ticket, then disable donation goal
        if instance.id is None:
            self.fields['donation_goal'].disabled = True


class BugForm(forms.ModelForm):
    """
    Bug ticket form
    """
    class Meta:
        """
        Fields to include on form
        """
        model = Bug
        exclude = ['ticket']

threads/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.template.context_processors import csrf
from .forms import ThreadForm, PostForm
from threads.models import Subject, Post, Thread
from django.forms import formset_factory
from polls.forms import PollSubjectForm, PollForm
from polls.models import PollSubject


def forum(request):
    return render(request, 'forum/forum.html', {'subjects': Subject.objects.all()})

def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'forum/threads.html', {'subject': subject})


@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    poll_subject_formset_class = formset_factory(PollSubjectForm, extra=3)
    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = poll_subject_formset_class(request.POST)
        if (thread_form.is_valid() and
                post_form.is_valid() and
                poll_form.is_valid() and
                poll_subject_formset.is_valid()):
            thread = thread_form.save(False)
            thread.subject = subject
            thread.user = request.user
            thread.save()

            post = post_form.save(False)
            post.user = request.user
            post.thread = thread
            post.save()

            poll = poll_form.save(False)
            poll.thread = thread
            poll.save()

            for subject_form in poll_subject_formset:
                subject = subject_form.save(False)
                subject.poll = poll
                subject.save()

            messages.success(request, "You have created a new thread!")

            return redirect(reverse('thread', args=[thread.pk]))

    else:
        thread_form = ThreadForm()
        post_form = PostForm()
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset_class()

    args = {
        'thread_form': thread_form,
        'post_form': post_form,
        'subject': subject,
        'poll_form': poll_form,
        'poll_subject_formset': poll_subject_formset,
    }

    args.update(csrf(request))

    return render(request, 'forum/thread_form.html', args)

def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)
    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'forum/thread.html', args)

@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form': form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)

@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "You have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)

    args = {
        'form': form,
        'form_action': reverse('edit_post', kwargs={"thread_id": thread.id, "post_id": post.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def delete_post(request, thread_id, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))


@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)

    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You already voted on this! ... You’re not trying to cheat are you?")
        return redirect(reverse('thread', args={thread_id}))

    subject = PollSubject.objects.get(id=subject_id)

    subject.votes.create(poll=subject.poll, user=request.user)

    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))

templates/forum/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block head_js %}
    <script src='{% static 'js/crossfilter.js' %}'></script>
    <script src='{% static 'js/d3.js' %}'></script>
    <script src='{% static 'js/dc.js' %}'></script>
    <script src='{% static 'js/queue.js' %}'></script>
    <script src='{% static 'js/keen.min.js' %}'></script>
    <script src='{% static 'js/dashboard_graph.js' %}'></script>
{% endblock head_js %}
{% block content %}
<div class='jumbotron' style='background: url("/static/img/jumbotrons/charting.jpg") no-repeat center center;background-size: cover; margin-bottom: 13px'>
    <h1>Work Dashboard</h1>&nbsp &nbsp<i class='fas fa-chart-bar'></i>
</div>
<div class='row'>
    <!-- Focus Bar Chart -->
    <div class='col-md-12'>
        <div class='chart-wrapper'>
            <div class='chart-title'>
                Ticket Event History <i class='fas fa-question-circle' data-toggle='tooltip' data-placement='right' title='Did you know that you can pan and zoom the Ticket Event History graph? Scroll up on the mouse wheel to zoom in on the timeline.
        Scroll down to zoom out. Click and drag the mouse to the left or right to see the oldest and newest tickets.'></i>
            </div>
            <div class='chart-stage'>
                <div id='focusChart'></div>
            </div>
        </div>
    </div>
    <!-- Focus Bar Chart -->
</div>
<div class='row'>
    <!-- Overview Bar Chart -->
    <div class='col-md-12'>
        <div class='chart-wrapper'>
            <div class='chart-stage'>
                <div id='overviewChart'></div>
            </div>
        </div>
    </div>
    <!-- Overview Bar Chart -->
</div>
<div class='row'>
    <!-- Ticket Type Row Chart -->
    <div class='col-md-6'>
        <div class='chart-wrapper'>
            <div class='chart-title'>
                Ticket Events By Type
            </div>
            <div class='chart-stage'>
                <div id='ticketTypeChart'></div>
            </div>
        </div>
    </div>
    <!-- Ticket Type Row Chart -->
    <!-- Ticket Status Row Chart -->
    <div class='col-md-6'>
        <div class='chart-wrapper'>
            <div class='chart-title'>
                Ticket Events by Status
            </div>
            <div class='chart-stage'>
                <div id='statusChart'></div>
            </div>
        </div>
    </div>
    <!-- Ticket Status Row Chart -->
</div>
<div class='row'>
    <!-- Ticket Hours Row Chart -->
    <div class='col-md-12'>
        <div class='chart-wrapper'>
            <div class='chart-title'>
                Ticket Hours Logged
            </div>
            <div class='chart-stage'>
                <div id='ticketHoursChart'></div>
            </div>
        </div>
    </div>
    <!-- Ticket Hours Row Chart -->
</div>
{% endblock %}

templates/forum/donation_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block content %}
<div class='col-md-8 offset-md-2 message-margin'>
    <h1 style='font-weight: 300'>Thanks for donating to our app!</h1>
    <h3 style='font-weight: 700'>{{ ticket.name }}</h3>
    <p style='font-weight: 300'><strong>Description: </strong>{{ ticket.description | striptags }}</p>
    <p style='font-weight: 300'>The amount donated will be charged to the default card on your <a href='{% url 'profile' %}'>profile</a> page</p>
    <form method='post' action='{% url 'custom_donate' ticket.id subject.id %}'>
        {% csrf_token %}
        <div class='form-group'>
            <label for='amount'>Donation Amount: </label>
            <input type='number' id='amount' name='amount' required='' min=10 step=10 oninvalid="this.setCustomValidity('Please enter amounts in intervals of $10')" oninput="this.setCustomValidity('')"></input>
            <br>
            <p style='font-weight: 700'>For every $10 that you donate, one vote will be cast for this feature.</p>
        </div>
        <div class='form-group'>
            <button type='submit' class='btn btn-success'>Donate</button>
        </div>
    </form>
</div>
{% endblock %}

templates/forum/forum.html
{% extends 'base.html' %}
{% load ticket_extras %}
{% load bootstrap_tags %}
{% block content %}
<section class='subject'>
    <table width='100%'>
        <tr>
            <th></th>
            <th>Tickets</th>
            <th>Posts</th>
        </tr>
        {% for subject in subjects %}
        <tr>
            <td>
                <h2><a href='{% url 'tickets' subject.id %}'>{{ subject.name }}</a></h2>
                <p>
                    <a href='{% url 'tickets' subject.id %}'>
                    {% autoescape off %}{{ subject.description }}{% endautoescape %}
                    </a>
                </p>
            </td>
            <td>{{ subject.tickets.count }}</td>
            <td>{{ subject|get_total_subject_posts }}</td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

templates/forum/post.html
{% load staticfiles %}
{% load emoticons_tags %}
{% load ticket_extras %}

<div class='col-md-12'>
    <table class='table table-sm' width='100%'>
        <thead class='thead-light'>
            <tr>
                <th class='text-left' style='min-width: 200px;max-width: 300px;'>{{ post.user.username }}<br>Posts: {{ post.user.posts.count }}</th>
                <th class='text-left'>
                    <time datetime='{{ post.created_at }}'>Posted: {{ post.created_at|started_time }}
                    </time>
                </th>
                {% if post.user == user or user.is_staff %}
                <th class='text-center'><a href='{% url 'edit_post' ticket.id post.id %}' data-toggle='tooltip' title='Edit Post'><i class='fas fa-edit'></i></a></th>
                <th class='text-center'><a href='#confirmationModal' role='button' data-toggle='modal' data-href='{% url 'delete_post' ticket.id post.id %}'><i style='color: red' class='fas fa-trash' data-toggle='tooltip' title='Delete Post'></i></a></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% autoescape off %}
                <td colspan='6' style='background-color: lightcyan'>{{ post.comment | striptags | linebreaks }}</td>
                {% endautoescape %}
            </tr>
        </tbody>
    </table>
    <br>
</div>
<!-- Modal -->
<div class='modal fade' id='confirmationModal' tabindex='-1' role='dialog' aria-labelledby='confirmationModalLabel' aria-hidden='true'>
    <div class='modal-dialog' role='document'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h5 class='modal-title' id='modalTitle'>Confirm</h5>
                <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden='true'>&times;</span>
                </button>
            </div>
            <div class='modal-body'>
                Are you sure you want to delete this post?
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-dismiss='modal'>Cancel</button>
                <form id='modalForm' action='' method='post'>
                    {% csrf_token %}
                    <button type='submit' class='btn btn-primary'>Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/forum/post_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block head_js %}
<script src='{% static 'js/tinymce/tinymce.min.js' %}'></script>
<script type='text/javascript'>
    tinyMCE.init({
        mode: 'textareas',
        theme: 'modern',
        plugins: 'paste',
        height: '300',
        content_css: '{% static 'css/tinymce.css' %}'
    });
</script>
{% endblock %}
{% block content %}
<section id='postform'>
    <div class='col-md-8 offset-md-2 message-margin'>
        <form method='post' action='{{ form_action }}'>
            <legend>Post Details</legend>
            {% csrf_token %}
            {{ post_form|as_bootstrap }}
            <div class='form-group'>
                <button type='submit' class='btn btn-success'>{{button_text}}</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/forum/progress_report.html
{% extends "base.html" %}
{% load ticket_extras %}
{% load stripe_extras %}
{% block content %}
 <div class="row header jumbotron">
   <div><h1 style="display: inline-block">{{ subject.name }} Report</h1>&nbsp &nbsp<i style="display: inline-block;" class="glyphicon glyphicon-stats"></i></div>
 </div>
 <!---This is the poll chart -->
{#% for subject in subjects %#}
 <div class="row">
     <div class="col-md-12">
        {% if subject.poll %}
           <div class="container">
               <h2 align="left">{{ subject.poll.question }}</h2>
               <div class="col-md-6">
                   {#% for option in options|slice:":5" %#}
                   {% for option in options %}
                       <div>
                           <div class="col-md-10">
                               <a href="{% url 'ticket' option.ticket_id %}"><strong>{{ option.ticket.name }}</strong></a>
                               <span class="pull-right">{{ option|vote_percentage|floatformat:2 }}%</span>
                           </div>
                           <div class="col-md-10">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-info" role="progressbar"
                                    aria-value="{{ option|vote_percentage }}" aria-valuemin="0"
                                    aria-valuemax="100" style="width:{{ option|vote_percentage }}%;">
                                    </div>
                                </div>
                           </div>
                       </div>
                  {% endfor %}
               </div>
               <div class="col-md-6">
                   {% for option in options %}
                       {% if subject.name == 'Feature' %}
                           <div class="col-md-10">
                                <strong>Donated: ${{ option.ticket.feature.total_donations|floatformat:2 }}</strong>
                                <span class="pull-right">Donation Goal: ${{ option.ticket.feature.donation_goal|floatformat:2 }}</span>
                           </div>
                           <div class="col-md-10">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-info" role="progressbar"
                                    aria-value="{{ option.ticket|donation_percentage }}" aria-valuemin="0"
                                    aria-valuemax="100" style="width:{{ option.ticket|donation_percentage }}%;">
                                    </div>
                                </div>
                           </div>
                       {% endif %}
                  {% endfor %}
               </div>
           </div>
        {% endif %}
     </div>
 </div>
{#% endfor %#}
 <!---This is the poll chart -->
{% endblock %}

templates/forum/thread.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thread_extras %}
{% block content %}

   <div class="row header">
       <div class="container">
           <h2>{{ thread.name }}</h2>
           <div class="col-md-12">
               <table class="table">
                   <tbody>
                   <tr>
                       <th>CREATED</th>
                       <th>OWNER</th>
                       <th>LAST POST</th>
                   </tr>
                   <tr>
                       <td>
                           <time datetime="{{ thread.created_at }}">
                           </time>
                       </td>
                       <td>{{ thread.user.username }}</td>
                       <td>{% last_posted_user_name thread %}</td>
                   </tr>
                   </tbody>
               </table>
           </div>
           {% if thread.poll %}
               <div class="container">
                   <div class="col-md-6">
                       <h2>Poll</h2>
                       <strong>{{ thread.poll.question }}</strong><br><br>

                       <p>Here’s how the votes are so far:</p>
                     {% for subject in thread.poll.subjects.all %}
                           <div class="col-md-10">
                               <strong>{{ subject.name }}</strong>
                               <span class="pull-right">{{ subject|vote_percentage }}%</span>
                           </div>

                           {% autoescape off %}
                           {% user_vote_button thread subject user %}
                           {% endautoescape %}

                        <div class="col-md-10">
                         <div class="progress">
                           <div class="progress-bar progress-bar-info" role="progressbar"
                            aria-value="{{ subject|vote_percentage }}" aria-valuemin="0"
                            aria-valuemax="100" style="width:{{ subject|vote_percentage }}%;">
                           </div>
                         </div>
                        </div>
                      {% endfor %}
                   </div>
               </div>
           {% endif %}

           {% if user.is_authenticated %}
               <p>
                   <a href="{% url 'new_post' thread.id %}" class="btn btn-primary">New post</a>
               </p>
           {% endif %}
       </div>
   </div>
   <div class="container">
       {% for post in thread.posts.all %}
           {% include "forum/post.html" %}
       {% endfor %}
   </div>
{% endblock %}

templates/forum/thread_form.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}
 
{% block head_js %}
   <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script type="application/javascript">
       tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})

   </script>
{% endblock %}


{% block content %}
    <section>
       <div class="col-md-9">
           <form method="post" action="{% url 'new_thread' subject.id %}">
               {% csrf_token %}
               <div class="form-group">
                   {{ thread_form | as_bootstrap }}
                   <hr>
                   {{ post_form | as_bootstrap }}
               </div>
               <div id="poll_form" class="form-group">
                   {{ poll_form|as_bootstrap }}
                   {{ poll_subject_formset.management_form }}
                   {% for poll_subject_form in poll_subject_formset %}
                       {{ poll_subject_form|as_bootstrap }}
                   {% endfor %}
               </div>
               <div class="form-group">
                   <button type="submit" class="btn-primary"> Post New Thread</button>
               </div>
           </form>
       </div>
    </section>
    <script>
        function showOrHidePollForm() {
            if ($('#id_is_a_poll').is(':checked')) {
                $('#poll_form').show();
                $('#id_question').prop("disabled", false);
            } else {
                $('#poll_form').hide();
                $('#id_question').prop("disabled", true);
            }
        }
        $(document).ready(showOrHidePollForm);
        $('#id_is_a_poll').change(showOrHidePollForm);
    </script>
{% endblock %}

templates/forum/threads.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
 <div class="row header">
   <div class="jumbotron"><h1>{{ subject.name }}</h1></div>
 </div>
 <div class="col-md-12">
   {% if user.is_authenticated %}
     <p>
       <a href="{% url 'new_thread' subject.id %}" class="btn btn-primary">New Ticket</a>
     </p>
   {% endif %}
   {% for thread in subject.threads.all %}
     {% include "forum/thread_item.html" %}
   {% endfor %}
 </div>
{% endblock %}